### PR TITLE
Fix Debugger memory contents inspection

### LINKED ISSUE #146: Fix Debugger memory contents inspection
Debugger and its REPL is helpful for debugging contract execution.
The problem is that it's `m` (memory inspection) command sometimes failed to display the memory contents because of using the wrong function `String.to_charlist()`. My first guess is that it should be the `:binary.bin_to_list()` instead.

### PR DESCRIPTION
**Pull request by vyorkin**
resolves #146

### CODE REVIEW

File: apps/evm/lib/evm/debugger.ex [hunk 1]
```diff
@@ -518,6 +526,17 @@ defmodule EVM.Debugger do
     {machine_state, sub_state, exec_env}
   end
 
+  @spec to_ascii(String.t()) :: String.t()
+  defp to_ascii(codepoint) do
+    is_printable =
+      codepoint
+      |> :binary.bin_to_list()
```
Comment (vyorkin) [inline apps/evm/lib/evm/debugger.ex]: The actual fix
